services:
  insite:
    build: .
    platform: linux/x86_64
    environment:
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - INSCRIPTIS_HOST=inscriptis
      - SCRAPINGBEE_API_KEY=${SCRAPINGBEE_API_KEY}
      - LIGHTHOUSE_API_KEY=${LIGHTHOUSE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    restart: always
  minio:
    image: quay.io/minio/minio
    platform: linux/x86_64
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - insite_minio:/data

  inscriptis:
    platform: linux/x86_64
    image: ghcr.io/weblyzard/inscriptis:latest

volumes:
  insite_minio:
